spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dragon_proxy?useSSL=false
    username: root
    password: root
    platform: mysql
    initialize: false

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATA}?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    initialize: true
